steps:

- name: 'python:3.11-slim'
  id: 'Generate Data'
  entrypoint: 'python'
  args:
    - 'src/datasets.py'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Container Image'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/bird-train:latest'
    - '-f'
    - './dockerfiles/train.dockerfile'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Container Image'
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/bird-train:latest'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push to Artifact Registry'
  args:
    - 'push'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/proj-artifacts/train:latest'

images:
- 'gcr.io/$PROJECT_ID/bird-train:latest'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/proj-artifacts/train:latest'

options:
  logging: CLOUD_LOGGING_ONLY
