steps:
- name: 'python:3.11-slim'
  id: 'Generate Data'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      pip install --no-cache-dir torch torchvision timm pytorch-lightning fastai
      python src/datasets.py

- name: 'alpine'
  id: 'Verify Data'
  entrypoint: 'sh'
  args:
    - '-c'
    - 'ls -l && ls -l /workspace/data'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Container Image 1'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/bird-train:latest'
    - '-f'
    - './dockerfiles/train.dockerfile'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Container Image'
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/bird-train:latest'

images:
- 'gcr.io/$PROJECT_ID/bird-train:latest'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/proj-artifacts/train:latest'

options:
  logging: CLOUD_LOGGING_ONLY
