# config.yaml
worker_pool_specs:
  - machine_spec:
      machine_type: "n1-standard-4"
    replica_count: 1
    executor_image_uri: "gcr.io/your-project-id/your-image-name"  # Your Docker image URI
    python_module: "src/vertex_ai/main.py"  # Python module to run (entrypoint)
