name: "Run tests"

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt

    # Step to install Google Cloud SDK
    - name: Install Google Cloud SDK
      run: |
        echo "Installing Google Cloud SDK..."
        curl https://sdk.cloud.google.com | bash
        source $HOME/google-cloud-sdk/path.bash.inc

    - name: Authenticate with Google Cloud
      run: |
        echo "${{ secrets.GCLOUD_SERVICE_KEY }}" > $HOME/gcloud-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
        gcloud config set project keen-defender-448412-p6
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-key.json

    - name: Test with pytest
      run: |
        pytest -v
